# #gentoo-dev-help 
#Thouse the example will start the leds' it dosent give up/down etc...
## This should be useful still in starting a proper service none the less... 
##
echo -e '#!/bin/sh\necho 3 > /sys/class/leds/asus::kbd_backlight/brightness' > /etc/local.d/light.start && chmod +x /etc/local.d/light.start
